services:
  ionic:
    build: .
    container_name: ionic-app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8100:8100"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=2000
      - WATCHPACK_POLLING=true